### ISSUE TITLE
Training a new model

### ISSUE THREAD

**Issue by deyaa97** [brunapearson/mtrl-auto-uav#1]
Hello,
Thanks a lot for the interesting code and helpful comments.

I have a question, is it possible to train the model in a new environment and save the trained data?
Thanks!

**Comment by dvirus27** [comment]
I am trying to run the test code, but I am getting the following error:

Traceback (most recent call last):
File "test_mtrl.py", line 205, in
depth = client.simGetImages([airsim.ImageRequest("0", airsim.ImageType.DepthPerspective)])
File "/home/deepakprasad/mtrl-auto-uav-master/airsim/client.py", line 103, in simGetImages
responses_raw = self.client.call('simGetImages', requests, vehicle_name)
File "/home/deepakprasad/anaconda3/envs/mtrl/lib/python3.7/site-packages/msgpackrpc/session.py", line 41, in call
return self.send_request(method, args).get()
File "/home/deepakprasad/anaconda3/envs/mtrl/lib/python3.7/site-packages/msgpackrpc/future.py", line 45, in get
raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'simGetImages' was called with an invalid number of arguments. Expected: 2, got: 3

Can you help me to fix it?

**Comment by dvirus27** [comment]
Do you have the code for training?
